### ISSUE TITLE
目录结构讨论

### ISSUE THREAD

**Issue by i5ting** [17koa/koa2-startkit#3]
- public放外面是比较正常的，是静态资源
- views放到src里比较好
- test从src移到根目录会比较舒服

@wssgcg1213 你觉得呢？

**Comment by wssgcg1213** [comment]
恩,
这个目录结构我参考了thinkjs的实现

因为src目录是作为babel的sourceDir的, 所以我希望只在src内放置 ES2015的js/json 文件
也就是

```
src : ES6/7 
app: ES5 (compiled js)
```

test目录的话, 我原先也是放到外面的, 但是我希望能在用例中使用ES6语法, 所以才放到内部
好像mocha支持`--compilers js:babel-core/register`这个参数 @ http://www.ruanyifeng.com/blog/2015/12/a-mocha-tutorial-of-examples.html, 我回去试试, 把它挪出来 

view的话 放到src内的考虑是什么呢?

**Comment by wssgcg1213** [comment]
@i5ting 
另外 这样src和app的组合也是为了我最近在想办法实现类似 https://thinkjs.org/zh-cn/doc/2.2/debug.html 的断点调试, thinkjs 的developmoent 模式热加载是hook了 nodejs 原生 module 模块, 感觉还挺复杂的, 我需要花点时间去看一下 nodejs require 实现的文档

**Comment by i5ting** [comment]
去看一下rails吧，我不喜欢thinkjs，从thinkphp搞过来的那套，感觉怪怪的

**Comment by wssgcg1213** [comment]
恩，我经常用thinkphp也看过ror，tp的view也确实是在src(Application) 里面的，因为它是分模块的

我回头试试吧

**Comment by wssgcg1213** [comment]
test移出来了

babel 只能转换js, view目录下的模板文件不会被copy到app下面, 所以需要用gulp或者webpack来处理了. 暂时views目录还是放在外面吧
